
export const BINGO_CHOICES: string[] = [
    "Watched a video recommended by YouTube or TikTok.",
    "Used a Snapchat, Instagram, or TikTok filter on a photo or video.",
    "Asked Siri, Alexa, or Google Assistant a question.",
    "Unlocked a phone or device using your face or fingerprint.",
    "Had your phone use autocorrect to fix a spelling mistake.",
    "Used predictive text that suggested the next word in your sentence.",
    "Played against a computer-controlled opponent in a video game.",
    "Used a map app (like Google Maps or Waze) to find the fastest route.",
    "Listened to a personalized playlist created for you (like Spotify's \"Discover Weekly\").",
    "Seen an online ad for something you recently searched for.",
    "Had a streaming service (like Netflix or Hulu) automatically play the next episode.",
    "Used \"portrait mode\" on a camera to blur the background of a photo.",
    "Had an email automatically go to your \"spam\" or \"promotions\" folder.",
    "Received a \"friend suggestion\" on a social media app.",
    "Used a grammar checker (like Grammarly) on schoolwork.",
    "Talked to a customer service chatbot on a website.",
    "Had your phone automatically group photos by the people in them.",
    "Used an app to translate a word into another language.",
    "Seen \"Customers also bought...\" recommendations on a shopping site.",
    "Used your voice to search for a show on a smart TV.",
    "Asked a smart speaker (like an Amazon Echo) for the weather forecast.",
    "Used a voice-to-text feature to write a message instead of typing it.",
    "Watched a video with automatically generated captions or subtitles.",
    "Asked a chatbot (like ChatGPT or Gemini) a question out of curiosity.",
    "Used an app like Shazam to identify a song that was playing.",
    "Watched a \"memories\" or \"year in review\" video made automatically from your photos.",
    "Had a sentence automatically completed for you in an email or document.",
    "Used a search engine that gave you the answer directly at the top of the page.",
    "Asked a smart device to set a timer or alarm for you.",
    "Used a \"magic eraser\" tool to remove an unwanted object from a photo.",
    "Scanned a document using your phone's camera.",
    "Used a suggested, one-tap reply to a text message or email.",
    "Had a music app create a \"radio station\" for you based on one song.",
    "Seen a fraud alert from a banking or payment app.",
    "Used an AI image generator to create a picture from a text description.",
    "Searched your phone's photos by typing a word like \"dog\" or \"beach.\"",
    "Played a digital game of chess or checkers against a computer.",
    "Read a news feed that was personalized for you.",
    "Used an app to virtually try on glasses or see furniture in your room.",
    "Received a \"nudge\" from an app reminding you to reply to a message."
];
